// Regenerates database/seed.sql from assets/js/mock-data.js so the database and the demo (mock) mode hold the same records.
// Usage:  node database/make-seed.js        (no dependencies)
// Dates are written relative to CURDATE() so the demo data always looks current.
const fs = require('fs');
const path = require('path');
const raw = require('../assets/js/mock-data.js').raw();

// bcrypt hashes of the demo passwords: demo1234 (customers) and admin1234 (staff)
const HASH = { customer: '$2b$10$rt.E5bauo8b2JHhe.0ie2O2yCubXQ8a0KJJDhVa7nSzJv6XDR5sKO', staff: '$2b$10$GRNWvGFLEUnYmd.Fw1eQXeZraJ9xe00MVLbHmDcqgFchfWTC97Gwi' };

const q = (v) => (v == null ? 'NULL' : typeof v === 'number' ? String(v) : "'" + String(v).replace(/\\/g, '\\\\').replace(/'/g, "''") + "'");
const at = (h) => (h == null ? 'NULL' : `DATE_ADD(CURDATE(), INTERVAL ${h} HOUR)`);
const insert = (table, cols, rows) => rows.length ? `INSERT INTO ${table} (${cols.join(', ')}) VALUES\n${rows.map((r) => '  (' + r.join(', ') + ')').join(',\n')};\n\n` : '';

let sql = '-- LockerGo demo data. GENERATED by database/make-seed.js from assets/js/mock-data.js — do not edit by hand.\n';
sql += "-- Demo accounts (username / password): user / demo1234 (customer), admin / admin1234 (super admin)\nUSE lockergo;\nSET NAMES utf8mb4;\nSET FOREIGN_KEY_CHECKS = 0;\nTRUNCATE settings; TRUNCATE activity_log; TRUNCATE promo_codes; TRUNCATE pricing; TRUNCATE payments; TRUNCATE bookings; TRUNCATE lockers; TRUNCATE locations; TRUNCATE users;\nSET FOREIGN_KEY_CHECKS = 1;\n\n";

sql += insert('users', ['id', 'username', 'name', 'email', 'phone', 'role', 'status', 'password_hash', 'notify_email', 'notify_sms', 'created_at', 'last_login_at'],
  raw.users.map((u) => [u.id, q(u.username), q(u.name), q(u.email), q(u.phone), q(u.role), q(u.status), q(u.role === 'customer' ? HASH.customer : HASH.staff), u.notifyEmail, u.notifySms, at(u.createdH), at(u.lastLoginH)]));
sql += insert('locations', ['id', 'name', 'address', 'zones', 'open_hours', 'phone'], raw.locations.map((l) => [l.id, q(l.name), q(l.address), q(l.zones), q(l.openHours), q(l.phone)]));
sql += insert('lockers', ['id', 'code', 'location_id', 'size', 'zone', 'status'], raw.lockers.map((l) => [l.id, q(l.code), l.locationId, q(l.size), q(l.zone), q(l.status)]));
sql += insert('bookings', ['id', 'ref', 'user_id', 'customer_name', 'customer_email', 'customer_phone', 'locker_id', 'start_at', 'end_at', 'duration_type', 'quantity', 'amount', 'discount', 'promo_code', 'status', 'pin', 'created_at'],
  raw.bookings.map((b) => [b.id, q(b.ref), b.userId, q(b.customerName), q(b.customerEmail), q(b.customerPhone), b.lockerId, at(b.startH), at(b.endH), q(b.durationType), b.quantity, b.amount, b.discount, q(b.promoCode), q(b.status), q(b.pin), at(b.createdH)]));
sql += insert('payments', ['id', 'booking_id', 'amount', 'method', 'status', 'created_at'], raw.payments.map((p) => [p.id, p.bookingId, p.amount, q(p.method), q(p.status), at(p.createdH)]));
sql += insert('pricing', ['size', 'hour_price', 'day_price', 'month_price'], raw.prices.map((p) => [q(p.size), p.hour, p.day, p.month]));
sql += insert('promo_codes', ['id', 'code', 'type', 'value', 'active', 'expires_at'], raw.promos.map((p) => [p.id, q(p.code), q(p.type), p.value, p.active, at(p.expiresH)]));
sql += insert('activity_log', ['id', 'actor_id', 'actor_name', 'action', 'target', 'created_at'], raw.activity.map((a) => [a.id, a.actorId, q(a.actor), q(a.action), q(a.target), at(a.createdH)]));
sql += insert('settings', ['k', 'v'], Object.entries(raw.settings).map(([k, v]) => [q(k), q(JSON.stringify(v))]));

fs.writeFileSync(path.join(__dirname, 'seed.sql'), sql);
console.log('seed.sql written:', Object.entries(raw).map(([k, v]) => `${k}=${Array.isArray(v) ? v.length : Object.keys(v).length}`).join(' '));
